camera0: "rtsp://192.168.144.26:8554/main.264"
camera1: "rtsp://192.168.144.2:8554/main.264"
frame_width: 1280
frame_height: 720
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 2
checkerboard_box_size_scale :  0.03
checkerboard_rows: 4
checkerboard_columns: 6
cooldown: 100
