camera0 = "/dev/camera_esquerda"
camera1 = "/dev/camera_direita"
frame_width: 1280
frame_height: 720
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 2
checkerboard_box_size_scale :  0.03
checkerboard_rows: 4
checkerboard_columns: 6
cooldown: 100
